---
galaxy_info:
  author: Srivatsav
  description: apache hadoop role
  company: I-590
  license:
    
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 21
    - name: Ubuntu
      versions:
        - trusty

  categories:
    - development

dependencies: []
  
